mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

# pulsar配置
pulsar:
  service-url: pulsar://192.168.0.1:30000

